omid_shop_category:
    resource: "@OmidShopBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

omid_shop_product:
    resource: "@OmidShopBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

omid_frontend:
    resource: Omid\ShopBundle\Controller\FrontedController
    type: annotation